### ISSUE TITLE
Miri flag passing changed

### ISSUE THREAD

**Issue by RalfJung** [vorner/bumpalo-herd#2]
`cargo miri test` changed to be more compatible with `cargo test`, but this means we had to find a different way to pass flags to the interpreter, so there now is a `MIRIFLAGS` environment variable for that. The old way still works for now, but is deprecated.

This affects the following line:
https://github.com/vorner/bumpalo-herd/blob/3590e4edf69f85a66bfb9768c4b0f2e71e19ae72/ci-check.sh#L20
This should now be `cargo miri test miri` (running the same tests as `cargo test miri`).

**Comment by vorner** [comment]
Thank you for letting me know.
